import React, { useEffect, useState } from 'react'
import Head from 'next/head'

import ethLogo from '../assets/ETH-LOGO.png'
import Image from 'next/image'

import { Network, Alchemy } from "alchemy-sdk"
import GetBlockByHash from '../components/GetBlockByHash'

const settings = {
  apiKey: process.env.ALCHEMY_API_KEY,
  network: Network.ETH_SEPOLIA,
};

const alchemy = new Alchemy(settings)

export default function Home() {

  const [latestBlock, setLatestBlock] = useState<string | undefined>()
  const [blockProperties, setBlockProperties] = useState<object | undefined>()

  async function getLatestBlock() {
    const latestBlock = (await alchemy.core.getBlockNumber()).toString()
    console.log("The latest block number is", latestBlock)

    setLatestBlock(latestBlock)
  }

  useEffect( () => {
    getLatestBlock()
  })

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <div className='flex flex-row justify-center items-center bg-slate-400 text-white py-4 gap-5'>
          <h3 className='text-xl'>Latest ETH Block: {latestBlock ? latestBlock : '...'}</h3>
          <Image src={ethLogo} alt={'ETH LOGO'} width={50} />
        </div>

        <GetBlockByHash blockProperties={blockProperties} setBlockProperties={setBlockProperties} alchemy={alchemy} />

      </main>
    </div>
  )
}
