import React, { useEffect, useState } from 'react'

import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Network, Alchemy } from "alchemy-sdk"

const settings = {
  apiKey: process.env.ALCHEMY_API_KEY,
  network: Network.ETH_SEPOLIA,
};

const alchemy = new Alchemy(settings)

export default function Home() {

  // const [latestBlock, setLatestBlock] = useState(0)

  async function getLatestBlock() {
    const latestBlock = await alchemy.core.getBlockNumber()
    console.log("The latest block number is", latestBlock.toString())

    // setLatestBlock(latestBlock)
  }

  useEffect( () => {
    getLatestBlock()
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          {/* <span>Latest ETH Block: {latestBlock ? latestBlock : '...'}</span> */}
        </div>
      </main>
    </div>
  )
}
